backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "新闻"
    folder: "/"
    create: true
    slug: "news-{{year}}-{{month}}-{{slug}}"
    extension: "html"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "摘要", name: "description", widget: "text"}
      - {label: "正文", name: "body", widget: "markdown"}
